[package]
name = "duxa-os"
version = "0.1.0"
edition = "2021"

[dependencies]
# No dependencies needed for now

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

[build]
target = "i686-unknown-none"